version: '3'

services:
  redis-1:
    image: redis:6.0
    command: --port 7001 --cluster-enabled yes
    container_name: redis-1
    restart: always
    ports:
      - 7001:7001
    networks:
      vpcbr:
        ipv4_address: 10.5.0.11
  redis-2:
    image: redis:6.0
    command: --port 7002 --cluster-enabled yes
    container_name: redis-2
    restart: always
    ports:
      - 7002:7002
    networks:
      vpcbr:
        ipv4_address: 10.5.0.12
  redis-3:
    image: redis:6.0
    command: --port 7003 --cluster-enabled yes
    container_name: redis-3
    restart: always
    ports:
      - 7003:7003
    networks:
      vpcbr:
        ipv4_address: 10.5.0.13
  redis-4:
    image: redis:6.0
    command: --port 7004 --cluster-enabled yes
    container_name: redis-4
    restart: always
    ports:
      - 7004:7004
    networks:
      vpcbr:
        ipv4_address: 10.5.0.14
  redis-5:
    image: redis:6.0
    command: --port 7005 --cluster-enabled yes
    container_name: redis-5
    restart: always
    ports:
      - 7005:7005
    networks:
      vpcbr:
        ipv4_address: 10.5.0.15
  redis-6:
    image: redis:6.0
    command: --port 7006 --cluster-enabled yes
    container_name: redis-6
    restart: always
    ports:
      - 7006:7006
    networks:
      vpcbr:
        ipv4_address: 10.5.0.16
  redis-cluster-proxy:
    image: adevjoe/redis-cluster-proxy:0.0.1
    command: 10.5.0.11:7001 10.5.0.12:7002 10.5.0.13:7003 10.5.0.14:7004 10.5.0.15:7005 10.5.0.16:7006
    container_name: redis-cluster-proxy
    restart: always
    ports:
      - 7777:7777
    networks:
      vpcbr:
        ipv4_address: 10.5.0.17
    depends_on:
      - redis-1
      - redis-2
      - redis-3
      - redis-4
      - redis-5
      - redis-6

networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1
