version: '3'

services:
  redis-1:
    image: redis:6.0
    command: --port 7001
    container_name: redis-data-1
    restart: always
    ports:
      - 8001:7001
  redis-2:
    image: redis:6.0
    command: --port 7002 --slaveof redis-data-1 7001
    container_name: redis-data-2
    restart: always
    ports:
      - 8002:7002
  redis-3:
    image: redis:6.0
    command: --port 7003 --slaveof redis-data-1 7001
    container_name: redis-data-3
    restart: always
    ports:
      - 8003:7003
  sentinel-1:
    image: redis:6.0
    command: /redis/sentinel.conf --port 7004 --sentinel
    container_name: sentinel-1
    restart: always
    ports:
      - 8004:7004
    volumes:
      - ./sentinel.conf:/redis/sentinel.conf
    depends_on:
      - redis-1
      - redis-2
      - redis-3
  sentinel-2:
    image: redis:6.0
    command: /redis/sentinel.conf --port 7005 --sentinel
    container_name: sentinel-2
    restart: always
    ports:
      - 8005:7005
    volumes:
      - ./sentinel.conf:/redis/sentinel.conf
    depends_on:
      - redis-1
      - redis-2
      - redis-3
  sentinel-3:
    image: redis:6.0
    command: /redis/sentinel.conf --port 7006 --sentinel
    container_name: sentinel-3
    restart: always
    ports:
      - 8006:7006
    volumes:
      - ./sentinel.conf:/redis/sentinel.conf
    depends_on:
      - redis-1
      - redis-2
      - redis-3

